on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller main.spec
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist/*
