on:
  push:
    tags:
      - "v*.*.*"

jobs:
  bundle:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller main.spec
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist/*
  
  release:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: Rename executables
      run: 'mv macos-latest/BruhGame BruhGame-macos-x86_64; mv windows-latest/BruhGame.exe BruhGame-win-x86_64.exe; mv ubuntu-latest/BruhGame BruhGame-ubuntu'
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          BruhGame-macos-x86_64
          BruhGame-win-x86_64.exe
          BruhGame-ubuntu
