on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller main.spec
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist/*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          pyglet_game/macos-latest/macos-latest
          pyglet_game/windows-latest/windows-latest
          pyglet_game/ubuntu-latest/ubuntu-latest
